apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  type: NodePort
  selector:
    app: config-service
  ports:
  - port: 4000
    name: http
    targetPort: 80
    protocol: TCP
    nodePort: 32570